<template>
  <!-- <v-content> -->
    <v-container fluid fill-height pa-0 ma-0>
      <v-layout align-center justify-center>
        <v-flex xs12>

          <v-dialog v-model="dialog" max-width="500px">

            <v-card>
              <v-card-title>
                <span class="headline">{{ $t('register.toc') }}</span>

              </v-card-title>

              <v-card-text>
                <p class="c1"><span class="c2">Deeds &amp; Needs is a student community platform. This Guideline will explain how Deeds &amp; Needs collects, uses and stores your personal information, along with the rights you are entitled to. We will use this Guideline to explain the relevant details, including the following:</span>
                </p>
                <p class="c5 c8"><span class="c2"></span></p>
                <ol class="c3 lst-kix_list_1-0 start" start="1">
                  <li class="c5 c9"><span class="c2">We will describe the types of personal information we collect and their corresponding use in order for you to understand how we collect specific type of personal information for a particular function, the reasons for its use and the methods of such collection.</span>
                  </li>
                  <li class="c5 c9"><span class="c2">While using some features, we will collect your personal information after obtaining your consent. Unless it is required by the relevant laws and regulations for you to provide such information, refusing to provide such information will only result in your not being able to use the specific functions relating to such information, but does not affect your normal use of other functions of Deeds &amp; Needs.</span>
                  </li>
                  <li class="c5 c9"><span class="c2">&nbsp;At present, Deeds &amp; Needs will not actively share or transfer your personal information to any third parties. Where the sharing or transferring of your personal information arises in some other situation, we will obtain your prior express consent.</span>
                  </li>
                  <li class="c5 c9"><span class="c2">At present, Deeds &amp; Needs will not actively obtain your personal information from a third party. If there is a requirement to obtain your personal information indirectly from a third party in future, we will clarify with you the source, type and scope of such personal information, For example, if the processing of personal information for a specific development is beyond the scope of what you originally agreed to provide to a third party, we will obtain your prior express consent before processing your personal information, and we will strictly abide by the relevant laws and regulations and require that the third party guarantees the legitimacy of the information provided.</span>
                  </li>
                  <li class="c5 c9"><span class="c2">You can access, correct and delete your personal information through the instructions listed in this Guideline, or you can withdraw your consent, cancel your account, report complaints and manage your privacy settings.</span>
                  </li>
                </ol>
                <p class="c5 c7"><span class="c2"></span></p>
                <hr style="page-break-before:always;display:none;">
                <p class="c1 c8"><span class="c2"></span></p>
                <p class="c1"><span class="c2">For more detailed information on the above, please refer to the relevant sections in following index:</span>
                </p>
                <ol class="c3 lst-kix_up4dykujowg4-0 start" start="1">
                  <li class="c5 c6"><span class="c2">Information We Collect</span></li>
                  <li class="c5 c6"><span class="c2">The Location and Time Period of Storing Information</span></li>
                  <li class="c5 c6"><span class="c2">Information Security</span></li>
                  <li class="c5 c6"><span class="c2">How We Use Information</span></li>
                  <li class="c5 c6"><span class="c2">External Parties</span></li>
                  <li class="c5 c6"><span class="c2">Your Rights</span></li>
                  <li class="c5 c6"><span class="c2">Amendments</span></li>
                  <li class="c5 c6"><span class="c2">Protection of minors</span></li>
                  <li class="c5 c6"><span class="c2">Contact us</span></li>
                </ol>
                <p class="c5 c8"><span class="c2"></span></p>
                <ol class="c3 lst-kix_vygqm1j5zsze-0 start" start="1">
                  <li class="c0"><span class="c4">Information We Collect</span></li>
                </ol>
                <p class="c1"><span class="c2">In the process of using Deeds &amp; Needs platform, Deeds &amp; Needs will, in accordance with the following ways, collect information provided by you during the use of the service or information generated by the use of the service, in order to provide such services to you, to optimize our services and protect your account security:</span>
                </p>
                <p class="c1"><span class="c2">1.1. When you register with Deeds &amp; Needs service, we will collect your name, profile picture and student ID picture in order to assist you completing Deeds &amp; Needs registration and to protect your Deeds &amp; Needs account security. Mobile phone numbers are considered to be sensitive information. As such, the collection of such information is to meet the relevant laws and regulations of the identity verification network system requirements. If you do not provide such information, you may not be able to use our services properly. You may also choose to fill in gender, region and other information in accordance to your own preference. </span>
                </p>
                <p class="c1"><span class="c2">1.2. When you use Deeds &amp; Needs platform, in order to ensure the normal use of our services, we will collect your device model, operating system, unique device identifier, login IP address, Deeds &amp; Needs version number, kind logs and other log information. Such information is required to provide you with Deeds &amp; Needs&rsquo;s platform and are basic information which must be collected.</span>
                </p>
                <p class="c1"><span class="c2">1.3. When you use the &quot;recommended contacts/friends&rdquo; function, we will conduct an irreversible encryption on your information, and only collect encrypted information. Such information is sensitive information, refusing to provide such information may result in you being unable to use the above function, but does not affect your normal use of Weixin&rsquo;s other functions.</span>
                </p>
                <p class="c5 c8"><span class="c2"></span></p>
                <p class="c1"><span class="c4">2. Storage of Information</span></p>
                <p class="c1"><span class="c2">2.1 &nbsp;Where Information is Stored</span></p>
                <p class="c1"><span class="c2">We will act in accordance with laws and regulations and store personal information collected within the territory in Asia.</span>
                </p>
                <p class="c1"><span class="c2">2.2 &nbsp;The Duration Storing Information</span></p>
                <p class="c1"><span class="c2">In general, we will only keep your personal information for the time necessary to achieve a specific purpose, for example:</span>
                </p>
                <p class="c1"><span class="c2">Student ID picture: When you use Deeds &amp; Needs platform, we will need to store your Student ID picture to ensure your normal use of the service and your safety in case of fraud; when you delete your Deeds &amp; Needs account, we will delete the corresponding information;</span>
                </p>
                <p class="c1"><span class="c2">In the event where we cease our products or services, we will notify you in the form of push notifications, announcements, etc., and delete your personal information or anonymize such information within a reasonable period of time.</span>
                </p>
                <p class="c5 c8"><span class="c2"></span></p>
                <p class="c1"><span class="c4">3.Information Security</span></p>
                <p class="c1"><span class="c2">We strive to secure users&#39; information to prevent information leakage, improper use, unauthorized access or disclosure.</span>
                </p>
                <p class="c1"><span class="c2">We will use a variety of security measures to ensure the security of information within reasonable security standards.</span>
                </p>
                <p class="c1"><span class="c2">We have set up specialized management systems, processes and organizations to ensure the security of information. For example, we strictly limit the range of people who may access such information and require them to comply with the confidentiality obligations and conduct audits.</span>
                </p>
                <p class="c1"><span class="c2">In the case of information leakage or other incidents involving information security, we will initiate contingency plans to prevent the wide spread of security incidents and inform you in the form of push notifications and announcements.</span>
                </p>
                <p class="c5 c8"><span class="c2"></span></p>
                <p class="c1"><span class="c4">4.How We Use Information</span></p>
                <p class="c1"><span class="c2">We may use information collected by certain features for our other services. For example, we may use the information we collect when you use one of our features, and provide you with specific content in another service, including, but not limited to display ads in another service.</span>
                </p>
                <p class="c1"><span class="c2">In order to ensure the security of our services, and to enable us to better understand the operations of our platform, we may record information such as your frequency of using our platform, crash logs, overall usage, performance data, and the sources that apps are installed from. We will not combine the information stored in the analytics software with any personally identifiable information you provide in the application.</span>
                </p>
                <p class="c1"><span class="c2">Where we utilize your personal information beyond the scope of our collection statement or a direct or reasonable connection, we will inform you and obtain your prior express consent again before using your personal information in such situations.</span>
                </p>
                <p class="c5"><span class="c2">&nbsp;</span></p>
                <p class="c1"><span class="c4">5.External Parties</span></p>
                <p class="c1"><span class="c2">At present, we will not actively share or transfer your personal information to a third party. If there are other circumstances in which your personal information is to be shared or transferred, we will obtain your prior express consent.</span>
                </p>
                <p class="c1"><span class="c2">We will not publicly disclose personal information collected by us. If we have to disclose such information publicly, we will inform you of the purpose of such disclosure, type of information disclosed and the sensitive information that may be involved, and obtain your prior express consent.</span>
                </p>
                <p class="c1"><span class="c2">As our business continues to develop, we may engage in mergers, acquisitions, transfers of assets, etc. We will inform you of such circumstances and continue to protect your personal information and require new controllers to continue to protect your personal information in accordance with the laws and regulations and the standards as strict as required by this Guideline.</span>
                </p>
                <p class="c5"><span class="c2">&nbsp;</span></p>
                <p class="c1"><span class="c4">6.Your Rights</span></p>
                <p class="c1"><span class="c2">During your course of using Deeds &amp; Needs, in order to provide you with an easier way to access, change, delete your personal information while ensuring you with the right to withdraw your consent regarding the use of personal information and the right to cancel your account, we have provided you with the applicable function when designing the product. </span>
                </p>
                <p class="c5"><span class="c2">&nbsp;</span></p>
                <p class="c5 c11"><span class="c4">7.Amendments</span></p>
                <p class="c1"><span class="c2">We may revise this Guideline in due course. In the event where the terms of this Guideline are amended, we will show you amended Guideline by way of push notifications and/or pop-up windows when you log in or when the platform version has been updated. Please note that we will follow the updated Guideline to collect, use and store your personal information only after you have tapped on the consent button in the pop-up window.</span>
                </p>
                <p class="c5 c11"><span class="c4">&nbsp;</span></p>
                <p class="c5 c11"><span class="c4">8. Protection of minors &nbsp;</span></p>
                <p class="c1"><span class="c2">We place great importance in the protection of personal information of minors. If you are a minor under the age of 14, according to the relevant laws and regulations, you can not be user of Deeds &amp; Needs platform </span>
                </p>
                <p class="c5 c8"><span class="c2"></span></p>
                <p class="c1"><span class="c4">9.Contact us</span></p>
                <p class="c1"><span class="c12">If you have any other complaints&#65292; suggestions&#65292; or querries regarding personal information of minors, please contact us at </span><span
                  class="c10">deedsandneeds1@gmail.com</span><span class="c2">. </span></p>
                <p class="c1"><span class="c2">We will review your queries as soon as possible and respond within 7 days after verifying your identity.</span>
                </p>
              </v-card-text>
              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn  flat @click.native="dialog=false"
                round color="#01B1C1" outline
                ><span style="font-size: 12px" class="black--text">
                {{$t('base.ok')}}
                </span>
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>

          <v-card>
            <v-toolbar>
              <v-toolbar-title>{{$t("register.form")}}</v-toolbar-title>
            </v-toolbar>

            <v-card-text>
              <v-form v-model="valid" ref="form" lazy-validation>


                <v-text-field
                  :counter="100" required :rules="rules.name"
                  v-model="user.username" prepend-icon="person" :label="$t('register.username')"
                  type="text"></v-text-field>
                <v-text-field
                  :counter="100" required :rules="rules.email"
                  v-model="user.email" prepend-icon="email" :label="$t('register.email')"
                  type="text"></v-text-field>

                <v-text-field
                  :counter="100" required :rules="rules.name"
                  v-model="user.name" prepend-icon="person" :label="$t('register.name')"
                  type="text"></v-text-field>

                <v-text-field
                  :counter="100" required :rules="rules.name"
                  v-model="user.secondname" prepend-icon="person" :label="$t('register.secondname')"
                  type="text"></v-text-field>

                <v-select
                  v-model="user.univerId"
                  item-text="title" item-value="id"
                  :items="univers" prepend-icon="work"
                  :rules="rules.requiredSelect"
                  :label="$t('register.university')"
                  required

                ></v-select>
                <v-select
                  v-model="user.lang" prepend-icon="language"
                  :items="langItems"
                  :rules="rules.requiredSelect"
                  :label="$t('register.lang')"
                  required

                ></v-select>
                <v-text-field
                  :counter="100" required :rules="rules.name"
                  v-model="user.studentid" prepend-icon="credit_card" name="login" :label="$t('register.studentid')"
                  type="text"></v-text-field>
                <v-text-field
                  required :rules="rules.name"
                  v-model="user.wechatid" prepend-icon="chat" name="wechatid" :label="$t('register.wechatid')"
                  type="text"></v-text-field>
                <v-text-field
                  required  :rules="rules.name"
                  v-model="user.phone" prepend-icon="phone" name="phone" :label="$t('register.phone')"
                  type="text"></v-text-field>
                <v-text-field
                  :counter="100" required :rules="rules.password"
                  min="8"
                  counter
                  :append-icon="e1 ? 'visibility' : 'visibility_off'"
                  :type="e1 ? 'password' : 'text'"
                  :append-icon-cb="() => (e1 = !e1)"
                  v-model="user.password" prepend-icon="security" name="login" :label="$t('register.password')"
                ></v-text-field>
                
                

                <vue-dropzone @vdropzone-file-added="addFile" ref="uploader" id="dropzone" :options="dropzoneOptions"></vue-dropzone>
              </v-form>
            </v-card-text>
            <v-card-actions>
              <!-- <v-spacer></v-spacer> -->
              <data-load ref="loader" suburl="/api/register/common" :loading.sync="loading" v-model="data"
                         :params="params">
              </data-load>

              <v-layout column>
                <v-flex xs12 >

                <v-btn active-class="red-text" @click="dialog=true" :loading="loading"
                flat round color="#01B1C1" outline>
                  <span style="font-size: 12px" class="black--text">
                  {{$t('register.toc')}}
                  </span>
                </v-btn>

                </v-flex>

                <v-flex xs12>
                  <v-layout align-center>
                    <v-flex xs6 >
                      <div align="right">
                      <v-card flat width="120">
                        <v-switch
                  :label="$t('register.agreement')"
                  v-model="agreement"
                ></v-switch>
                      </v-card>
                      </div>
                      
                    </v-flex>


                    <v-flex xs6 >
                      <div align="left">
                        <v-card flat width="110">
                          <v-btn  active-class="red-text" :disabled="!agreement" @click="register" :loading="loading"
              flat round color="#01B1C1" outline
              ><span style="font-size: 12px" class="black--text">
                {{$t('right.register')}}
                </span>
                          </v-btn>
                          
                          <v-dialog
      v-model="dlg_after_reg"
      width="500"
    >
      

      <v-card>
        <v-card-title
          class="headline grey lighten-2"
          primary-title
        >
          Registration Success
        </v-card-title>

        <v-card-text>
          Thank you for registration!<br>
            The email has been sent to your mailbox successfully. <br>
            If you haven't received the email, please check your spam or bulk mail folders.<br>
            Through a few hours you will get the email with a moderating status.<br>
            Please login to continue.



        </v-card-text>

        <v-divider></v-divider>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn
            
            
            @click="dlg_after_reg = false"
            :to="'/services'"
            flat round color="#01B1C1" outline
          >
            Ok
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>




                        </v-card>
                      </div>
                    </v-flex>
                  </v-layout>
                  

                </v-flex>
              </v-layout>
              
              

            </v-card-actions>


          </v-card>
        </v-flex>
      </v-layout>
    </v-container>
  <!-- </v-content> -->

</template>

<script>
  import CommonMixin from '@/mixins/common';

  import axios from 'axios'
  import vue2Dropzone from 'vue2-dropzone'
  import 'vue2-dropzone/dist/vue2Dropzone.min.css'
  import router from "@/router";

  import DataLoad from '@/common/data-loader'
  import {EventBus} from '@/event-bus'
  import {loadValidations} from '@/mixins/validation-rules'
  export default {
    mixins: [CommonMixin],
    components: {
      'data-load': DataLoad,
      'vue-dropzone': vue2Dropzone
    },
    $_veeValidate: {
      validator: 'new'
    },
    data () {
      return {

        dlg_after_reg:false,
        e1: true,

        dialog: false,
        agreement: false,

        rules: loadValidations(this),
        valid: false,
        data: {},

        user: {
          name: "",
          password: "",
          univerId: null,
          lang: null,
          studentId: null,
          username: null,
          email: null
        },
        params: "lang=" + this.$i18n.locale,
        loading: true,
        msg: ''
      }
    },
    computed: {
      langItems(){
        return this.langs.map((i) => {
          return {

            text: this.$t('langs.' + i.lang), value: i.lang
          }
        });
      },

    },
    mounted () {
      EventBus.$emit('change-title', "register.form");

    },
    created: function () {
      EventBus.$on('update-locale', lang => {
        this.params = "lang=" + lang;
      });

    },
    methods: {
      addFile(file, error, xhr){
        console.log("addFile", file, error, xhr);
        if (file.size > 5 * 1024 * 1024) {
          this.$refs.uploader.removeFile(file);
          this.$dialog.alert(this.$t('profile.cannotaddbigfile'), {
            cancelText: this.$t("base.cancel")
          })


        }
      },
      register(){
        


        if (!this.$refs.form.validate())
          return;
        this.snackbar = true;
        this.text = "sdfsdf";

        console.log(this.$refs.uploader.getQueuedFiles());
        let formData = new FormData();

        for (var i in this.user) {
          formData.append(i, this.user[i]);
        }
        this.$refs.uploader.getQueuedFiles().forEach((f, i) => formData.append("file", f));


        axios.post('/api/register/signup',
          formData,
          {
            headers: {
              'Content-Type': 'multipart/form-data'
            }
          }
        ).then(res => {

          if (res.data.success) {
            this.dlg_after_reg = true;
            //EventBus.$emit('show-message', {color: "info", text: "register.success"});
            //router.push('/login');
          }
        })
          .catch(error => {
            EventBus.$emit('error', error);
          })

      },
      clear () {
        this.name = '';
        this.email = '';
        this.select = null;
        this.checkbox = null
      }


    }
  }
</script>
