package com.dan.exception;

public enum AppError {
    CANNOT_SWITCH_STATUS, ACCESS_TO_DEAL_NOT_PERMITTED, CANNOT_USER_INITIATOR, NEW_DEAL_NOT_ALLOWED, NOT_ENOGHT_MONEY, BLOCKED_SUM_LESS_THAN_UNBLOCK, studentid_already_exist, email_already_exist, login_already_exist, DEAL_NOT_FOUND, CANNOT_FIND_MODERATOR, CANNOT_FIND_MODERATOR_RECORD, REVIEW_BY_DEAL_EXISTS, ACCESS_DENIED, CLAIM_ALREADY_POSTED, CLAIM_REVIEW_ALREADY_POSTED, CANNOT_TAKE_CREDIT_THAN_MAX, NOT_ENOGHT_MONEY_TO_SOLVE_CREDIT, CANNOT_FIND_CURATOR, CONFLICT_IS_ALREADY_PROCESSED_BY_MAIN_CURATOR, REVIEW_NOT_ALLOW, NO_CURATOR_FOR_THIS_UNIVER, UNIVER_ALREADY_EXISTS, USER_NOT_MODERATED, BAD_EMAIL, BAD_EMAIL_OR_VERIFY, NOT_AUTH_ACCESS
}
